type = "class object"
name = "Person"
code = "class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n        self.gender = \"female\"\n\n    def set_name(self, name):\n        self.name = name\n"

[attrs]
age = 19
gender = "female"
name = "Pavel"
